### ISSUE TITLE
Performance with an intensive stream 

### ISSUE THREAD

**Issue by DmitryAstafyev** [esrlabs/logviewer#191] opened 2018-04-16 13:18 UTC
# Requested feature / improvements 
With the intensive stream, logviewer works extremely slow (especially on win platform).

## Solution
Add buffer on service side:
- collect data to stream until buffer size or timeout
- send to front-end package 

## Affected parts
- telnet stream
- terminal stream
- serial port stream

**Comment by marcmo** [comment] 2018-07-18 11:11
duplicate of #176

**Closed by marcmo** 2018-07-18 11:11 UTC
Labels: enhancement
